# -*- coding: utf-8 -*-
"""proj.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kxAE0P5k4beP-VmpWlPlZUA-XGeQI6Hd
"""

!pip install chatterbot

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
from chatterbot.comparisons import JaccardSimilarity
#from chatterbot.trainers import ChatterBotCorpusTrainer

hotelbot = ChatBot(
    'hotelbot',
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch',
            'statement_comparison_function': JaccardSimilarity,
            'default_response': 'عذرخواهی می‌کنم. متوجه منظور شما نشدم.',
            'maximum_similarity_threshold': 0.70
        }
    ]
)
trainer = ListTrainer(hotelbot)
trainer.train([
    "سلام",
    "سلام. سامانه رزرواسیون هتل درخدمت شما است. درخواست شما چیست؟",             
    "می‌خواهم اتاق رزرو کنم.",
    "تاریخ شروع اقامت را بفرمایید.",
    "تاریخ شروع",
    "تاریخ پایان اقامت را بفرمایید.",
    "تاریخ پایان",
    "برای چند نفر در خواست اتاق دارید؟",
    "تعداد",
    "شماره تماس خود را بفرمایید.",
    "شماره تماس",
    "نام و نام خانوادگی شما چیست؟",
    " اسم کاربر",
    "آیا اطلاعات رزرواسیون را تایید مي‌کنید؟",
    "بله",
    "رزرو اتاق با موفقیت انجام شد."
])
trainer.train([
    "آیا اطلاعات رزرواسیون را تایید مي‌کنید؟",
    "اره",
    "رزرو اتاق با موفقیت انجام شد."
])
trainer.train([
    "آیا اطلاعات رزرواسیون را تایید مي‌کنید؟",
    "آره",
    "رزرو اتاق با موفقیت انجام شد."
])
trainer.train([
    "سلام",
    "سلام. سامانه رزرواسیون هتل درخدمت شما است. درخواست شما چیست؟",             
    "رزرو اتاق",
    "تاریخ شروع اقامت را بفرمایید."
])
trainer.train([
    "آیا اطلاعات رزرواسیون را تایید مي‌کنید؟",
    "خیر",
    "تاریخ شروع اقامت را بفرمایید."
])
trainer.train([
    "آیا اطلاعات رزرواسیون را تایید مي‌کنید؟",
    "نه",
    "تاریخ شروع اقامت را بفرمایید."
])
trainer.train([
    "تاریخ خطا",
    "تاریخ وارد شده قابل قبول نیست. لطفا دوباره وارد نمایید.",
])
trainer.train([
    "تلفن تماس خطا",
    ". لطفا دوباره وارد نمایید. شماره تماس قابل قبول نیست."
])
trainer.train([
    "خطا نفرات",      
    "تعداد افراد را صحیح وارد کنید."
])
trainer.train([
    "بازه ی خطا",      
    "بازه ی زمانی قابل قبول نیست. مجددا تاریخ شروع اقامت را وارد کنید.",
])
trainer.train([
    "خطای رزرو"
    "این درخواست رزرو قابل انجام نیست. اتاق کافی در این تاریخ وجود ندارد. چه درخواست دیگری دارید؟"
])

def is_date(st):
  day31=['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور']
  day30=['مهر','آبان','آذر','دی','بهمن','ابان','اذر']
  day29=['اسفند']

  if len(st)!=3:
    return False
  if st[0]<1:
    return False
  if st[1] in day31 and st[0]>31:
    return False
  elif st[1] in day30 and st[0]>30:
    return False
  elif st[1] in day29 and st[0]>29:
    return False
  elif st[1] not in day31+day30+day29:
    return False
  return True
  
calender = {'فروردین':1,
            'اردیبهشت':2,
            'خرداد':3,
            'تیر':4,
            'مرداد':5,
            'شهریور':6,
            'مهر':7,
            'آبان':8,
            'ابان':8,
            'آذر':9,
            'اذر':9,
            'دی':10,
            'بهمن':11,
            'اسفند':12}

def acceptable_period(s,f):
  if s[2]>f[2]:
    return False
  if calender.get(s[1])>calender.get(f[1]) and s[2]==f[2]:
    return False
  if s[0]>f[0] and s[1]==f[1] and s[2]==f[2]:
    return False
  return True

def check_availability(reserv):
  # a function to test if reservation is available 
  # checks for available rooms in hotel db
  # must be implemented to return True or False
  return True

def save_reservation(reserv):
  # fuction to enter reservation data in hotel db
  # must be implemented to return True or False as for successful reservation is done
  return True

def print_reservation(reserv):
  print()
  print("نام و نام خانوادگی : {}".format(reserv[0]))
  print("شماره همراه : {}".format(reserv[4]))
  print("از تاریخ : {}".format(reserv[1]))
  print("تا تاریخ : {}".format(reserv[2]))
  print("نفرات : {}".format(reserv[3]))
  return

def clean(txt):
  new_txt = ''
  stop_wrds = ['نفر','انجام','از','تا','هستم','هست']
  for w in txt.split():
    if w not in stop_wrds:
      new_txt += ' '+w
  return new_txt.strip()

import math

phone_flag = False
start_date_flag = False
end_date_flag = False
people_flag = False
name_flag = False
final_flag = False
accept = ['بله','اره','آره']
save_flag = False
name= s_date= e_date= people= phone =0

print("شما به سامانه ی رزرواسیون متصل شدید ")
print('******')

while True:
    try:
        user_input = input()
        user_input = clean(user_input)

        if final_flag :
          if user_input in accept:
            if not check_availability(reservation):
              user_input = "خطای رزرو"
            else:
              save_flag = True
          final_flag = False

        if name_flag :
          name = user_input
          name_flag = False
          user_input = " اسم کاربر"

        if people_flag :
          if user_input.isnumeric() and int(user_input)>0:
            people = user_input
            people_flag = False
            user_input = "تعداد"
          else:
            user_input = "خطا نفرات"

        if phone_flag :
          if user_input.isnumeric() and int(math.log10(int(user_input)))==9:
            phone = user_input
            phone_flag = False
            user_input = "شماره تماس"
          else:
            user_input = "تلفن تماس خطا"

        if start_date_flag :
          st1 = user_input.split()
          st1[0] = int(st1[0])
          st1[2] = int(st1[2])
          if is_date(st1):
            s_date = user_input
            start_date_flag = False
            user_input = "تاریخ شروع"
          else:
            user_input = "تاریخ خطا"

        if end_date_flag :
          st2 = user_input.split()
          st2[0] = int(st2[0])
          st2[2] = int(st2[2])
          if is_date(st2):
            if acceptable_period(st1,st2):
              e_date = user_input
              end_date_flag = False
              user_input = "تاریخ پایان"
            else:
              user_input = "بازه ی خطا"
              end_date_flag = False
              start_date_flag = True
          else:
            user_input = "تاریخ خطا"

        bot_response = hotelbot.get_response(user_input)

        if bot_response.text ==  "رزرو اتاق با موفقیت انجام شد." and save_flag:
          if save_reservation(reservation):
            print(bot_response)
          save_flag = False
          break
      
        if bot_response.text == "برای چند نفر در خواست اتاق دارید؟":
          people_flag = True

        if bot_response.text == "شماره تماس خود را بفرمایید.":
          phone_flag = True
          
        if bot_response.text == "تاریخ شروع اقامت را بفرمایید.":
          start_date_flag = True
        
        if bot_response.text ==  "تاریخ پایان اقامت را بفرمایید.":
          end_date_flag = True
        
        if bot_response.text == "نام و نام خانوادگی شما چیست؟":
          name_flag = True

        if bot_response.text == "آیا اطلاعات رزرواسیون را تایید مي‌کنید؟":
          final_flag = True
          reservation = (name, s_date, e_date, people, phone)
          print_reservation(reservation)      

        print(bot_response) 
       
    # Press ctrl-c or ctrl-d on the keyboard to exit
    except (KeyboardInterrupt, EOFError, SystemExit):
        break
print('******')
print("ارتباط با سامانه پایان یافت. از این که از خدمات این سامانه استفاده کردید سپاسگزاریم.")